customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.jpg
    favicon: /images/favicon.png # path to favicon
    social_links:
        github: http://github.com/johnnynotsolucky
        twitter: https://twitter.com/tyronetudehope
    post_count: 10

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
